[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
rustflags = [
#"-C", "link-arg=/SUBSYSTEM:WINDOWS",
#    "-C", "link-arg=-static-libgcc",
#    "-C", "link-arg=-lmupdf",
#    "-C", "debug-assertions=false",
"-C","link-arg=-fuse-ld=lld",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-args=-mmacosx-version-min=10.15",
]

[target.x86_64-apple-darwin]
rustflags = [
    "-C", "link-args=-mmacosx-version-min=10.15",
]

#[env]
#MACOSX_DEPLOYMENT_TARGET = "10.15"
